import { Blog } from './types';

export const blogs: Blog[] = [
  {
    id: 1,
    title: "The Art of Perfect Espresso: A Complete Guide",
    slug: "art-of-perfect-espresso-guide",
    excerpt: "Master the fundamentals of espresso making with our comprehensive guide covering everything from bean selection to machine maintenance.",
    content: "Espresso is more than just coffee - it's an art form that requires precision, patience, and passion...",
    author: "Sarah Johnson",
    authorAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    category: "Coffee Techniques",
    tags: ["espresso", "coffee", "brewing", "tutorial"],
    featuredImage: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&h=400&fit=crop",
    status: "published",
    publishedAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    views: 2847,
    likes: 156,
    comments: 23,
    isFeatured: true,
    seoTitle: "Perfect Espresso Guide - Coffee Brewing Techniques",
    seoDescription: "Learn how to make perfect espresso with our step-by-step guide covering equipment, techniques, and troubleshooting tips.",
    readingTime: 8
  },
  {
    id: 2,
    title: "Sustainable Coffee Farming: Impact on Quality",
    slug: "sustainable-coffee-farming-impact",
    excerpt: "Explore how sustainable farming practices not only benefit the environment but also enhance coffee quality and flavor profiles.",
    content: "Sustainable coffee farming is revolutionizing the industry, creating better coffee while protecting our planet...",
    author: "Michael Chen",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    category: "Sustainability",
    tags: ["sustainability", "farming", "environment", "quality"],
    featuredImage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=400&fit=crop",
    status: "published",
    publishedAt: "2024-01-12T14:30:00Z",
    updatedAt: "2024-01-12T14:30:00Z",
    views: 1923,
    likes: 89,
    comments: 15,
    isFeatured: false,
    seoTitle: "Sustainable Coffee Farming - Environmental Impact",
    seoDescription: "Discover how sustainable coffee farming practices improve both environmental health and coffee quality.",
    readingTime: 6
  },
  {
    id: 3,
    title: "Coffee Shop Design Trends 2024",
    slug: "coffee-shop-design-trends-2024",
    excerpt: "Discover the latest design trends shaping modern coffee shops, from minimalist aesthetics to sustainable materials.",
    content: "Coffee shop design has evolved significantly, reflecting changing consumer preferences and values...",
    author: "Emma Rodriguez",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    category: "Design",
    tags: ["design", "trends", "interior", "coffee-shop"],
    featuredImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=400&fit=crop",
    status: "draft",
    publishedAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
    views: 0,
    likes: 0,
    comments: 0,
    isFeatured: false,
    seoTitle: "Coffee Shop Design Trends 2024 - Interior Inspiration",
    seoDescription: "Explore the latest coffee shop design trends including minimalist aesthetics, sustainable materials, and modern layouts.",
    readingTime: 5
  },
  {
    id: 4,
    title: "The Science Behind Coffee Roasting",
    slug: "science-behind-coffee-roasting",
    excerpt: "Dive deep into the chemical reactions that occur during coffee roasting and how they affect flavor development.",
    content: "Coffee roasting is a complex process involving numerous chemical reactions that transform green beans...",
    author: "David Park",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    category: "Science",
    tags: ["roasting", "science", "chemistry", "flavor"],
    featuredImage: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=400&fit=crop",
    status: "published",
    publishedAt: "2024-01-10T11:15:00Z",
    updatedAt: "2024-01-10T11:15:00Z",
    views: 3456,
    likes: 203,
    comments: 31,
    isFeatured: true,
    seoTitle: "Coffee Roasting Science - Chemical Reactions & Flavor",
    seoDescription: "Understand the science behind coffee roasting and how chemical reactions create the flavors we love.",
    readingTime: 12
  },
  {
    id: 5,
    title: "Cold Brew vs Iced Coffee: What's the Difference?",
    slug: "cold-brew-vs-iced-coffee-difference",
    excerpt: "Learn the key differences between cold brew and iced coffee, including brewing methods, flavor profiles, and best uses.",
    content: "While both cold brew and iced coffee are served cold, they're completely different beverages...",
    author: "Lisa Wang",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    category: "Coffee Types",
    tags: ["cold-brew", "iced-coffee", "comparison", "brewing"],
    featuredImage: "https://images.unsplash.com/photo-1517701604599-bb29b565090a?w=800&h=400&fit=crop",
    status: "published",
    publishedAt: "2024-01-08T16:20:00Z",
    updatedAt: "2024-01-08T16:20:00Z",
    views: 1789,
    likes: 94,
    comments: 18,
    isFeatured: false,
    seoTitle: "Cold Brew vs Iced Coffee - Complete Comparison Guide",
    seoDescription: "Discover the differences between cold brew and iced coffee, including brewing methods and flavor profiles.",
    readingTime: 4
  },
  {
    id: 6,
    title: "Coffee Culture Around the World",
    slug: "coffee-culture-around-world",
    excerpt: "Take a journey through different coffee cultures worldwide, from Italian espresso bars to Ethiopian coffee ceremonies.",
    content: "Coffee culture varies dramatically around the world, reflecting local traditions and preferences...",
    author: "Ahmed Hassan",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    category: "Culture",
    tags: ["culture", "traditions", "global", "ceremony"],
    featuredImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&h=400&fit=crop",
    status: "archived",
    publishedAt: "2023-12-28T13:45:00Z",
    updatedAt: "2023-12-28T13:45:00Z",
    views: 2156,
    likes: 127,
    comments: 22,
    isFeatured: false,
    seoTitle: "Global Coffee Culture - Traditions & Ceremonies",
    seoDescription: "Explore coffee cultures worldwide from Italian espresso to Ethiopian ceremonies and beyond.",
    readingTime: 7
  },
  {
    id: 7,
    title: "Building a Home Coffee Station",
    slug: "building-home-coffee-station",
    excerpt: "Create the perfect home coffee station with our guide to essential equipment, organization tips, and space planning.",
    content: "A well-designed home coffee station can transform your daily coffee routine into a delightful experience...",
    author: "Jennifer Lee",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    category: "Home Brewing",
    tags: ["home", "equipment", "organization", "setup"],
    featuredImage: "https://images.unsplash.com/photo-1559056199-5c63ed4c4dac?w=800&h=400&fit=crop",
    status: "published",
    publishedAt: "2024-01-05T08:30:00Z",
    updatedAt: "2024-01-05T08:30:00Z",
    views: 1234,
    likes: 67,
    comments: 12,
    isFeatured: false,
    seoTitle: "Home Coffee Station Setup - Complete Guide",
    seoDescription: "Learn how to build the perfect home coffee station with equipment recommendations and organization tips.",
    readingTime: 6
  },
  {
    id: 8,
    title: "The Future of Coffee Technology",
    slug: "future-coffee-technology",
    excerpt: "Explore emerging technologies in the coffee industry, from smart grinders to AI-powered brewing systems.",
    content: "Technology is revolutionizing how we grow, process, and brew coffee, opening new possibilities...",
    author: "Robert Kim",
    authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    category: "Technology",
    tags: ["technology", "innovation", "future", "automation"],
    featuredImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    status: "draft",
    publishedAt: "2024-01-25T12:00:00Z",
    updatedAt: "2024-01-22T14:20:00Z",
    views: 0,
    likes: 0,
    comments: 0,
    isFeatured: false,
    seoTitle: "Coffee Technology Future - Smart Brewing & AI",
    seoDescription: "Discover the latest coffee technology innovations including smart grinders and AI-powered brewing systems.",
    readingTime: 9
  }
];

export const blogStatuses = [
  { id: 'published', label: 'Published', color: 'success' },
  { id: 'draft', label: 'Draft', color: 'warning' },
  { id: 'archived', label: 'Archived', color: 'muted' }
];

export const adminBlogCategories = [
  'Coffee Techniques',
  'Sustainability', 
  'Design',
  'Science',
  'Coffee Types',
  'Culture',
  'Home Brewing',
  'Technology'
];

export const blogAuthors = [
  'Sarah Johnson',
  'Michael Chen', 
  'Emma Rodriguez',
  'David Park',
  'Lisa Wang',
  'Ahmed Hassan',
  'Jennifer Lee',
  'Robert Kim'
];

export const blogSortOptions = [
  { id: 'title', label: 'Title A-Z' },
  { id: 'publishedAt', label: 'Publish Date' },
  { id: 'views', label: 'Most Views' },
  { id: 'likes', label: 'Most Liked' },
  { id: 'comments', label: 'Most Comments' },
  { id: 'readingTime', label: 'Reading Time' }
];

export const blogFilterConfig = {
  searchPlaceholder: 'Search blogs...',
  statusLabel: 'Status',
  categoryLabel: 'Category', 
  authorLabel: 'Author',
  sortLabel: 'Sort by'
};
